apiVersion: v1
kind: Service
metadata:
  name: requestprinter
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: requestprinter
