name: Release new version

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "go.mod"
      - "main.go"

concurrency:
  group: main

jobs:
  release:
    name: Tag the commit and push the tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Bump the tag
        id: tag
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "/^major:/"
          minor_pattern: "/^minor:/"

      - name: Tag and push to remote
        run: |-
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          generated_tag="${{ steps.tag.outputs.version_tag }}"

          if git tag --points-at HEAD | grep -w "${generated_tag}"; then
            echo "Tag ${generated_tag} already exists, skipping"
          else
            git tag ${generated_tag}
            git push origin ${generated_tag}
          fi
